# Generated by Django 4.2.3 on 2023-07-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparaciones',
            name='Valor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
